events {
    worker_connections 1024;
}

http {
    upstream emp_mail_cluster {
        # Utilisation des noms de services Docker Compose
        server mail-node-1:8080;
        server mail-node-2:8080;
        server mail-node-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://emp_mail_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
